### ISSUE TITLE
Determine origin and usage of icons included in project

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#1051]
## Problem
There are several icons included in the [`src/assets/icons/`](https://github.com/creativecommons/vocabulary/tree/main/src/assets/icons) directory from an unknown origin. In order to give proper attribution, we should determine the source of the icons as well as their license terms.

## Task

- [x] locate the originating project for non-CC icons located in `src/assets/icons`
- [x] determine license terms for the icons
- [x] determine how to include the icons in downstream projects
- [ ] identify any downstream Creative Commons projects that use the non-CC licenses, such as Chooser

**Comment by MuluhGodson** [comment]
@brylie 
## - locate the originating project for non-CC icons located in src/assets/icons
These icons are gotten from Font Awesome. It is referenced in this [commit](https://github.com/creativecommons/vocabulary/commit/4ff0e58ca64f0b85c2083417c407fd1194208103) made on Jul 18 2021 by @dhruvkb in the file `src/stories/vocabulary_svg_icons.stories.mdx`

## - determine license terms for the icons
Font Awesome's free license for their SVG icons is our `CC BY 4.0` license. Referenced here [Font Awesome Free Licenses](https://fontawesome.com/license/free)

**Comment by brylie** [comment]
Would it be feasible to directly link to the Font Awesome icons rather than include them in our source code?

**Comment by MuluhGodson** [comment]
yeah, I think that will work better for our use case. We aren't altering the icons in any way so importing FA and using the icons normally will be better, and also reduce file size.

**Comment by brylie** [comment]
I opened a related issue in the Chooser project: https://github.com/creativecommons/chooser/issues/378

**Comment by brylie** [comment]
Closing this since we identified FontAwesome as the icon source.
