### ISSUE TITLE
Adopt Prettier for code formatting

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#406]
We want to ensure clean and consistent code style/formatting. One simple step would be to add Prettier as a `devDependency` to the project. Prettier may already be a transient dependency of the Vue CLI, but we will need to verify whether this is true.

## Task

- [ ] add Prettier as a `devDependency` for this project
- [ ] add instructions to our README for the use of Prettier
- [ ] consider how to automate code formatting via Prettier (e.g. via Git hooks)
- [ ] consider whether it is necessary to modify our `ci-lint` script to validate code using Prettier

## Original issue
**Description**
Since the project is being actively worked on by many developers, we need to ensure code quality is maintained consistently across the project. This is most efficiently achieved by
- creating a code style document for developers to follow
- setting up ESLint to catch cases where the code style is being missed
- setting up more comprehensive tooling to catch these cases in PRs

**Problems solved**
A clear, organised and well-maintained codebase is always a joy to contribute to.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
I would like to work on this issue 
Can you please provide me with some pointers as if how to begin with same 
Thanks

**Comment by megha070** [comment]
@dhruvkb I would like to take this up.

**Comment by dhruvkb** [comment]
@kushaggarwal as this is a [`discussion:rfc`](https://github.com/creativecommons/vocabulary/labels/discussion%3Arfc), we start with a discussion. You come up with solutions and we triage them.

First explore the tools:
- [Code Climate](https://codeclimate.com/quality/)
- [Codecov](https://codecov.io/)
- [ESLint](https://eslint.org/)

**Comment by kushaggarwal** [comment]
Okay sure @dhruvkb 
Will work upon the same

**Comment by megha070** [comment]
I just wanted to inquire if we need to draft code style document according to the the errors as shown in below image. 
![image](https://user-images.githubusercontent.com/40516822/83939357-ee9a3400-a7f9-11ea-9cde-8aa7636319da.png)

**Comment by Dishebh** [comment]
@dhruvkb we can use `prettier` to make the code style consistent throughout. Also, can I work on integrating codecov and codeclimate in the repo?

**Comment by dhruvkb** [comment]
- Before we integrate Prettier, we need to under how drastically it changes the existing codebase. 
- Codecov does not make a lot of sense because we're not unit testing Sass that heavily and we reverted the visual regression tests. 
- Can you document what advantages would CodeClimate bring to the repository?

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
As guided by you I went through all the sources recommended by you previously
- For integrating lint check in the repository can you please help as if what configuration is to be followed regarding indentations and all 
- As per code cov it majorly deals with the code coverage for the repo which in this case can be achieved with the help of code climate too
-  For code review we can use code climate which inturn can check duplicate code and unused variables thus helping in proper check for the pull request being merged, also it provides us with code coverage for checking the parts of code currently associated with be respective tests

**Comment by dhruvkb** [comment]
It has come to my notice that ESLint does not support linting for Sass files. We can go with Prettier as @Dishebh suggested but it remains to be determined if that will change a lot of existing code because Prettier is an opinionated tool.

We don't want to be checking unit test coverage so does any of the tools Codecov and Code Climate give code quality information about Sass?

**Comment by Dishebh** [comment]
@dhruvkb, for starters, we can go with fixing the `tabWidth`, `printWidth`, `singleQuotes`, `trailingCommas` and `bracketSpacing`?

**Comment by dhruvkb** [comment]
@Dishebh makes sense. Please open a PR for this.

**Comment by kgodey** [comment]
We're going to be working on a style guide first before this is unblocked.

**Comment by brylie** [comment]
Repurposing this task to adopt Prettier for code formatting.

**Comment by Datagirlcmr** [comment]
I will love to work on this

**Comment by brylie** [comment]
Thanks, @Datagirlcmr! I'll assign you.

For what it's worth, our project seems to have Prettier as a transient dependency (perhaps of the Vue CLI or something similar). Please add a note to the documentation about how to format the project code with Prettier, as well as considering making Prettier a top-level dependency.

**Comment by Datagirlcmr** [comment]
#1009 create a prettier.MD file documenting how to use prettier to format code base

**Comment by Datagirlcmr** [comment]
It is true that formatting with prettier changes a lot on the codebase. How about I fix all errors and we adopt prettier for code formatting. I have already pulled the most recent changes on the repo

**Comment by brylie** [comment]
@Datagirlcmr, I've reviewed PR #1009 and requested changes to link it to this issue.

**Comment by brylie** [comment]
Closing, since we have recently adopted Prettier for code formatting.
