### ISSUE TITLE
Update contribution guide with development environment setup instructions

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#954]
We recently refactored the project but neglected to update the contribution guide. I.e., the README and contribution guide differ substantially, such as there being no Docker Compose file.

https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page
It would probably be a good idea to remove one of the two resources to prevent them from going out of sync.

## Task

- [ ] ensure the README contains accurate instructions for setting up a development environment
- [ ] if desirable, restore the Docker Compose file (for cases where `npm` is causing issues)
- [ ] copy any remaining salient information from the [Vocabulary / Contribution](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page) instructions to the README
- [ ] replace the Vocabulary / Contribution article with a link to the project README

**Comment by MuluhGodson** [comment]
I  am working on this.

**Comment by Akpjunior94** [comment]
Hello, I'm Abraham an Outreachy applicant I would like to take on this issue.

**Comment by brylie** [comment]
@MuluhGodson and @Akpjunior94, I've assigned you both. Please coordinate your work via the CC Community Slack :-)

**Comment by MuluhGodson** [comment]
okay @brylie

**Comment by Akpjunior94** [comment]
thanks @brylie
