### ISSUE TITLE
Restore deployment scripts for all packages

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#964]
The Vocabulary project consists of three sub-packages:

- fonts
- vocabulary
- vue-vocabulary

When making a release, we have a corresponding script to publish each package to NPM:

- https://github.com/creativecommons/vocabulary/blob/main/.github/workflows/cd-fonts.yml
- https://github.com/creativecommons/vocabulary/blob/main/.github/workflows/cd-vocabulary.yml
- https://github.com/creativecommons/vocabulary/blob/main/.github/workflows/cd-vue.yml

However, the bash scripts have been (re)moved in a recent refactor:

- https://github.com/creativecommons/vocabulary/blob/238a272adc1f942a43ca6d9d72f0ddabc08c9df4/.github/workflows/cd-fonts.yml#L31
- https://github.com/creativecommons/vocabulary/blob/238a272adc1f942a43ca6d9d72f0ddabc08c9df4/.github/workflows/cd-vocabulary.yml#L31
- https://github.com/creativecommons/vocabulary/blob/238a272adc1f942a43ca6d9d72f0ddabc08c9df4/.github/workflows/cd-vue.yml#L30

## Task

- [x] fix the `cd-fonts.yml` automation process by restoring the [`deploy.sh`](https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/fonts/deploy.sh) as `publish/fonts.sh`
- [x] fix the `cd-vocabulary.yml` automation process by restoring the [`deploy.sh`](https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vocabulary/deploy.sh) as `publish/vocabulary.sh`
- [x] fix the `cd-vue.yml` automation process by restoring the [`deploy.sh`](https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vue-vocabulary/deploy.sh) as `publish/vue-vocabulary.sh`
- [x] use "publish" instead of "deploy" wherever relevant to make it clear we are publishing a package

**Comment by MuluhGodson** [comment]
The deploy.sh file was what was refactored into scripts/build_fonts.sh and also for the rest.
When these changes were made at the time, the CI pipeline was not updated. 
The pipeline was written to still compile each package and test each package in its own sub-folder but the repository structure was already refactored into it's own monorepository with newer build scripts.

**Comment by brylie** [comment]
We need both `build` and `deploy` scripts:

- https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/fonts/deploy.sh#L20
- https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vocabulary/deploy.sh#L20
- https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vue-vocabulary/deploy.sh#L21

**Comment by brylie** [comment]
To save some confusion, let's rename the `deploy` script to `publish` to make it clear we are actually publishing to NPM.

**Comment by brylie** [comment]
@MuluhGodson, I've updated the issue description with links to the `deploy.sh` scripts.

**Comment by MuluhGodson** [comment]
Hello @brylie I will love to continue working on this

**Comment by brylie** [comment]
OK, great! I've assigned you,  @MuluhGodson :smile: 

Please start a fresh, or revise an existing, pull request so it is focused only on the task as outlined in the description for this issue:

![image](https://user-images.githubusercontent.com/17307/137091555-e71d8632-77d6-44a2-ad6d-6fa265d80817.png)
