### ISSUE TITLE
Restore project unit tests

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#965]
Our project consists of three sub-modules:

- fonts
- vocabulary
- vue-vocabulary

Each of the submodules used to have corresponding tests:

- [fonts](https://github.com/creativecommons/vocabulary/tree/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/fonts/tests)
- [vocabulary](https://github.com/creativecommons/vocabulary/tree/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vocabulary/tests)
- [vue-vocabulary](https://github.com/creativecommons/vocabulary/tree/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vue-vocabulary/tests)

The unit tests were invoked in relevant continuous integration scripts:

- [ci-fonts](https://github.com/creativecommons/vocabulary/blob/238a272adc1f942a43ca6d9d72f0ddabc08c9df4/.github/workflows/ci-fonts.yml#L74-L101)
- [ci-vocabulary](https://github.com/creativecommons/vocabulary/blob/238a272adc1f942a43ca6d9d72f0ddabc08c9df4/.github/workflows/ci-vocabulary.yml#L75-L102)
- [ci-vue-vocabulary](https://github.com/creativecommons/vocabulary/blob/238a272adc1f942a43ca6d9d72f0ddabc08c9df4/.github/workflows/ci-vue.yml#L74-L101)

## Task

- [ ] restore all testing code in a `tests/` directory in the root of this project
    - [ ] `tests/vue-vocabulary`
- [ ] ensure we have script(s) defined in `package.json` to invoke the test suites
    - [ ] `test:vue-vocabulary`
- [ ] update CI test runners to invoke restored tests
    - [ ] `ci-vue.yml` (rename to `ci-vue-vocabulary.yml`) 
- [ ] remove fonts tests, since `sass-jest` is no longer maintained 
    - [ ] delete `vocabulary/.github/workflows/ci-fonts.yml` 
    - [ ] delete `vocabulary/.github/workflows/ci-vocabulary.yml` 
- [ ] delete all unused scripts and code after refactoring tests

**Comment by MuluhGodson** [comment]
```bash
"scripts": {
    "lint": "eslint src/*.js src/**/*.js tests/**/*.js",
    "test:unit": "jest -c tests/unit/jest.config.js",
    "test:snapshot": "jest -c tests/snapshot/jest.config.js",
    "build": "webpack --mode production",
    "watch": "webpack --mode production --watch --progress",
    "storybook": "start-storybook --ci -s ./src/assets -p 8080 --quiet",
    "build:documentation": "npm run build && build-storybook -s ./src/assets -o ./docs"
  },
```
This code snippet above is from the package.json file that had the scripts to run the test. 
But if you notice, the test is run using a package configuration that is no longer used. `jest`

https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/fonts/package.json

**Comment by MuluhGodson** [comment]
@brylie I think the last time the former deployment scripts were being used was when this other PR was made:
https://github.com/creativecommons/vocabulary/pull/906

**Comment by MuluhGodson** [comment]
@brylie I set up all these test independently on my local environment and discovered these test were removed because the package used for test is no longer maintained. There were a lot of bugs especially related to incompatibilities. I checked the repository for the test package used and also noticed an issue was raised there but has not been resolved. I think the package owner will not be pursuing it any longer.

**Comment by MuluhGodson** [comment]
so the most appropriate way forward will be to write new test or find a similar but current testing package.

**Comment by brylie** [comment]
Alright, we should remove the CI step for now then. Let's repurpose this task to disable the CI script.

**Comment by brylie** [comment]
Which package is no longer maintained? There seem to be at least a couple of test frameworks used in the files above, Vue tests, SCSS tests, and perhaps vanilla JS tests (via Jest).

**Comment by brylie** [comment]
Jest seems to be alive and well

https://jestjs.io/

**Comment by MuluhGodson** [comment]
Jest is the package that I think has the problem. These packages were provided by vue-cli-service but I think VueJS is now on v3 and that should explain

**Comment by MuluhGodson** [comment]
Yeah Jest is fine, but the test used a package known as `sass-true` which lets the sass files be tested via jest

**Comment by brylie** [comment]
OK, shall we deprecate the `sass-true` tests and keep the other Vue / JS tests then? I'd like to preserve some of the tests if possible.

**Comment by MuluhGodson** [comment]
It's this sass-true package that makes testing with jest and the sass files buggy now
https://github.com/oddbird/true/issues/154

**Comment by MuluhGodson** [comment]
Yes I think we can keep the Vue/JS test alive.

**Comment by MuluhGodson** [comment]
So this issue is still very much valid

**Comment by brylie** [comment]
OK, great! I've updated the task checklist in the description to include "remove fonts tests" while restoring the other tests.

**Comment by MuluhGodson** [comment]
@brylie while going through the files I noticed the test for fonts and vocabulary was the same. So just the Vue-Vocabulary test is safe as of now.

So I want to request taking this issue to see how I can be able to rewrite some new test for the different packages. 

The PR that may be as a result of this may also handle #962

**Comment by brylie** [comment]
@MuluhGodson, I've assigned you to the task. Thanks!
