### ISSUE TITLE
Divide continuous integration scripts based on purpose: lint, test, and build

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#973]
Based on discussion in https://github.com/creativecommons/vocabulary/discussions/970, we agreed to divide our continuous integration actions based on their purpose:

- lint
- test
- build

## Task

- [ ] create three new GitHub actions files
    - [ ] `github/workflows/ci-lint.yml`
    - [ ] `github/workflows/ci-test.yml`
    - [ ] `github/workflows/ci-build.yml`
- [ ] configure each of the new GitHub actions based on the code below
- [ ] delete the old GitHub actions
    - [ ] `.github/workflows/ci-fonts.yml`
    - [ ] `.github/workflows/ci-vocabulary.yml` 
    - [ ] `.github/workflows/ci-vue.yml`

## Code

Below, you can find the specific code for each new CI file.

<details>

<summary>ci-lint.yml</summary>

```yaml
name: Lint

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --no-audit

  lint:
    name: Lint
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Run lint
        run: npm run lint
```
</details>

<details>

<summary>ci-test.yml</summary>

```yaml
name: Test

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --no-audit

  test:
    name: Test
    defaults:
      run:
        working-directory: "packages/fonts"
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Run tests
        run: npm run test:unit
```
</details>

<details>

<summary>ci-build.yml</summary>

```yaml
name: Build

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --no-audit

  build:
    name: Build
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v2

      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Run build
        run: npm run build:storybook
```
</details>

**Comment by Akpjunior94** [comment]
@brylie I will work on this. You can assign me

**Comment by brylie** [comment]
Closing this as it was completed by @MuluhGodson

**Comment by Akpjunior94** [comment]
> Closing this as it was completed by @MuluhGodson

No problem. I'm very sorry I Had issue with my screen since yesterday. It's fixed now.
