### ISSUE TITLE
Audit code coverage and automate coverage reporting

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#985]
We want to understand how extensively our code is covered by unit tests. To this end, we should generate an initial report. Furthermore, the reporting should be automated as part of our continuous integration process.

## Task

- [ ] choose a code coverage auditing tool
- [ ] run an initial coverage audit
- [ ] determine how to automate coverage auditing, e.g. as part of pull request reviews
- [ ] enable automated coverage auditing in our continuous integration (by adding a `ci-coverage.yml` workflow)
- [ ] use the current coverage report to create a list of tasks to add unit tests

**Comment by Onyimatics** [comment]
Hello @brylie, I'm an Outreachy applicant and I would like to take up this issue.

**Comment by brylie** [comment]
OK, thanks @Onyimatics! I'll assign you to this issue.

**Comment by Akpjunior94** [comment]
Hello @brylie can I join @Onyimatics to solve this Issue?

**Comment by brylie** [comment]
@Akpjunior94, please check with @Onyimatics to see how the might need assistance.

**Comment by Akpjunior94** [comment]
> @Akpjunior94, please check with @Onyimatics to see how the might need assistance.

Okay @brylie
