### ISSUE TITLE
Consolidate scripts into single directory

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#987]
We currently have several shell scripts in the following locations:

- `/publish.sh`
- `/scripts/build_*.sh`
- `/publish/<package-name>.sh`

These scripts are used by our GitHub Action workflows:

- https://github.com/creativecommons/vocabulary/tree/main/.github/workflows

## Task

- [ ] Reorganize scripts into a single directory, outlined below
- [ ] update GitHub workflows with the new script locations, to ensure the workflows still function
- [ ] delete the `publish.sh` in the project root directory, as it seems to be a duplicate of a publish script
- [ ] delete the `deploy.sh` in the project root directory, as it seems to be a duplicate of a publish script

## Desired directory structure

The scripts should be organized as follows:

- `/scripts/` - top level scripts directory
    -  `publish/` - publish subdirectory (within `/scripts/`)  
        - `fonts.sh`
        - `vocabulary.sh`
        - `vue-vocabulary.sh`
    - `build/` - build subdirectory (within `/scripts/`)
        - `fonts.sh` - renamed
        - `vocabulary.sh` - renamed
        - `vue-vocabulary.sh` - renamed and hyphenated

**Comment by waridrox** [comment]
Hi @brylie! 👋🏻 Can I take this up ?

**Comment by brylie** [comment]
@waridrox, thanks! I've assigned you to the issue.
