### ISSUE TITLE
Simplify project dependencies down to absolute minimum

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#990]
Our project has many `dependencies` and `devDependencies` defined in `package.json`. The complex nature of these dependencies along with transient dependencies is making the project difficult to maintain and upgrade. In order to promote maintainability and security, we should reduce our project down to the absolute minimum dependencies necessary. In this process, it will hopefully become possible to upgrade our dependencies to their latest secure versions as well.

## Task

- [ ] identify any non-essential `dependencies` and remove them from the project
- [ ] identify any non-essential `devDependencies` and remove them from the project
- [ ] move development dependencies from `dependencies` to `devDependencies` where relevant (such as `node-sass` or `eslint-plugin-jest`)
- [ ] upgrade our dependency tree to resolve as many vulnerabilities as possible with `npm audit fix --legacy-peer-deps`
- [ ] determine whether we can stop using the `--legacy-peer-deps` flag when managing our dependencies

## Related resources

We should make sure to follow the Storybook [Styling and CSS](https://storybook.js.org/docs/react/configure/styling-and-css) guidelines.

**Comment by emmaxy07** [comment]
I would like to work on this.

**Comment by brylie** [comment]
Thanks, @emmaxy07! I've assigned you to the issue. What will be the first steps you will take?

**Comment by Nurganym** [comment]
I would like to work on this.

**Comment by brylie** [comment]
Thanks @Nurganym . I'll assign you alongside @emmaxy07 . Please coordinate your efforts 😀

**Comment by possumbilities** [comment]
This project is moving towards being archived, and this item is no longer on the roadmap. Closing
